title: Brayden Hill
email: braydenhill.bgh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The present is a gift, and I just want to be. 

# Set up for GitHub Pages
baseurl: "/bradyghills"  # Change this to match your repo name
url: "https://bradyghills.github.io"  # Your GitHub Pages URL

twitter_username: jekyllrb
github_username: bradyghills

collections:
  writings:
    output: true
  trip-logs:
    output: true
    permalink: /outdoors/trip-logs/:name
  travel-logs:
    output: true
    permalink: /travel-logs/:name/

# Default Front Matter to recognize custom fields
defaults:
  - scope:
      path: ""
      type: "trip-logs"
    values:
      titleimage: ""

# Build settings
plugins:
  - jekyll-feed

# Exclusions
exclude:
  - _config_dev.yml  # Exclude the development config from GitHub Pages
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

