title: Brayden Hill
email: braydenhill.bgh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The present is a gift, and I just want to be. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. https://bradyghills.github.io
twitter_username: jekyllrb
github_username: bradyghills

collections:
  writings:
    output: true
  trip-logs:
    output: true
    permalink: /outdoors/trip-logs/:name
  travel-logs:
    output: true
    permalink: /travel-logs/:name/

# Default Front Matter to recognize custom fields
defaults:
  - scope:
      path: ""
      type: "trip-logs"
    values:
      titleimage: ""

# Build settings
plugins:
  - jekyll-feed

# Exclusions
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

